dist: xenial
sudo: required
language: generic

before_cache:
  - rm -rf $HOME/.opam/log
cache:
  apt: true
  directories:
  - $HOME/.opam
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
env:
  global:
  - NJOBS=2
  - EXT_LIB_TARGET="0.10.3"
  matrix:
  - TEST_TARGET="8.9.1"

before_script:
  -  ./ci/keep_alive.sh &

install:
  - opam init -n -y
  - eval $(opam config env)
  - opam config var root
  # this somehow fails the second time...
  - opam repo add coq-released http://coq.inria.fr/opam/released || true
  - opam install -y --verbose -j ${NJOBS} coq.${TEST_TARGET} && opam pin add coq ${TEST_TARGET} -y
  - opam install -y --verbose -j ${NJOBS} ocamlfind camlp5 ${EXTRA_OPAM} 
  - opam install -y --verbose -j ${NJOBS} coq-color
  - opam install -y --verbose -j ${NJOBS} coq-ext-lib.${EXT_LIB_TARGET} && opam pin add coq-ext-lib ${EXT_LIB_TARGET} -y
  - opam install -y --verbose -j ${NJOBS} coq-math-classes
  - opam install -y --verbose -j ${NJOBS} coq-metacoq-template
  - opam install -y --verbose -j ${NJOBS} coq-switch
  - opam install -y --verbose -j ${NJOBS} ANSITerminal
  - opam install -y --verbose -j ${NJOBS} coq-flocq
  - opam install -y --verbose -j ${NJOBS} coq-paco
  - opam install -y --verbose -j ${NJOBS} coq-ceres
  - opam install -y --verbose -j ${NJOBS} menhir
  - opam install -y --verbose -j ${NJOBS} core
  - opam install -y --verbose -j ${NJOBS} core_kernel
  - opam install -y --verbose -j ${NJOBS} dune

script:
  - eval $(opam config env)
  - opam config var root
  - git clone --recurse-submodules https://github.com/vellvm/vellvm.git lib/vellvm && make -j ${NJOBS} -C lib/vellvm/src
  - ln -s `pwd`/lib/vellvm/src/ml/libvellvm/ ml/
  - make -j ${NJOBS}
  - make test

notifications:
  slack: digamma-ai:UpxI6GZGpcU4NZi813AkDl0g
  