dist: xenial
sudo: required
language: generic

branches:
  only:
  - master
  
before_cache:
  - rm -rf $HOME/.opam/log
cache:
  apt: true
  directories:
  - $HOME/.opam
addons:
  apt:
    update: true
    sources:
    - sourceline: "ppa:avsm/ppa"
    packages:
    - opam
    - aspcud
env:
  global:
  - NJOBS=2
  matrix:
  - TEST_TARGET="8.12.0"

before_script:
  -  ./ci/keep_alive.sh &

install:
  - opam init -n -y --compiler=4.11.1+flambda
  - eval $(opam config env)
  - opam config var root
  # this somehow fails the second time...
  - opam repo add coq-released http://coq.inria.fr/opam/released || true
  - opam install -y --verbose -j 1 coq.${TEST_TARGET} && opam pin add coq ${TEST_TARGET} -y
  - opam install -y --verbose -j 1 ocamlfind camlp5 ${EXTRA_OPAM} 
  - opam install -y --verbose -j 1 coq-color
  - opam install -y --verbose -j 1 coq-ext-lib
  - opam install -y --verbose -j 1 coq-math-classes
  - opam install -y --verbose -j 1 coq-metacoq-template
  - opam install -y --verbose -j 1 coq-switch
  - opam install -y --verbose -j 1 ANSITerminal
  - opam install -y --verbose -j 1 coq-flocq
  - opam install -y --verbose -j 1 coq-paco
  - opam install -y --verbose -j 1 coq-ceres
  - opam install -y --verbose -j 1 coq-libhyps
  - opam install -y --verbose -j 1 menhir
  - opam install -y --verbose -j 1 core
  - opam install -y --verbose -j 1 core_kernel
  - opam install -y --verbose -j 1 dune
  - opam install -y --verbose -j 1 qcheck
  - opam update -y
  - travis_wait 90 opam upgrade -j 1 -y

script:
  - eval $(opam config env)
  - opam config var root
  - git clone --recurse-submodules https://github.com/vellvm/vellvm.git lib/vellvm
  - git --no-pager --git-dir=lib/vellvm/.git log -1 --pretty=oneline
  - make -j ${NJOBS} -C lib/vellvm/src
  - ln -s `pwd`/lib/vellvm/src/ml/libvellvm/ ml/
  - make -j ${NJOBS}
  - make test

notifications:
 slack: codemindersw:EqDgyov45kk75iskZ4lBLOhM
